name: Continuous Integration

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Run install and test
        run: |
          npm install
          npm run test
